version: "3.1"
services:
  webserver:
    build: .
    ports:
      - "80:80"
    volumes:
      - ../../easydev:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - database

  database:
    image: mariadb:10.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: blabla
      MARIADB_DATABASE: easydev0
      MARIADB_USER: easydev
      MARIADB_PASSWORD: t53cE56n6
    ports:
      - "3306:3306"
    volumes:
      - ../../databases:/docker-entrypoint-initdb.d
      - ./mariadb-configuration:/etc/mysql/conf.d:ro

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

