<?php
/*********************************************************************************
 * Autogenerated script
 * EasyDev 1.x copyright Patrick Mingard 2007-2008
 * Any modification of this code may alter the behaviour of EasyDev 1.x console
 ********************************************************************************/

require_once('includes/connection.php'); // includes the connection to the database
require_once('object_<% echo $this->name; %>.class.php');

if(isset($_GET['id'])){
  $object = <% echo $this->name; %>::findByPrimaryId($_GET['id']);
  if($object){
    header('Content-type: '.image_type_to_mime_type($object-><% echo $fieldname; %>_type));
    header('Content-disposition: inline');
    if(isset($_GET['width']) && $_GET['width'] > 0){
      $resource = imagecreatefromstring($object-><% echo $fieldname;%>);
      $w = imagesx($resource);
      $h = imagesy($resource);
      $newwidth = $_GET['width'];
      $newheight = $newwidth * $h / $w;
      if($resource){
        $resizedresource = imagecreatetruecolor($newwidth, $newheight);
        $status = imagecopyresized($resizedresource, $resource, 0, 0, 0, 0, $newwidth, $newheight, $w, $h);
        if($status){
          switch($object-><% echo $fieldname;%>_type){
          case IMAGETYPE_GIF:
            imagegif($resizedresource);
            break;
          case IMAGETYPE_JPEG:
            imagejpeg($resizedresource, null, 95);
            break;
          case IMAGETYPE_PNG:
            imagepng($resizedresource, null, 2);
            break;
          }
        }
      }
    }
    else{
      echo $object-><% echo $fieldname; %>;
    }
    exit();
  }
}   
echo '';

?>

