<?php
/*********************************************************************************
 * Autogenerated script
 * EasyDev v.1.x copyright Patrick Mingard 2007
 * Any modification of this code can alter the behaviour of EasyDev v.1.x console
 ********************************************************************************/

require_once('includes/connection.php'); // includes the connection to the database
require_once('object_<% echo $this->name; %>.class.php');

if(isset($_GET['id'])){
  $object = <% echo $this->name; %>::findByPrimaryId($_GET['id']);
  if($object){
    header('Content-type: '.image_type_to_mime_type($object-><% echo $fieldname; %>_type));
    header('Content-disposition: inline');

    echo $object-><% echo $fieldname; %>;
    exit();
  }
}   
echo '';

?>

