<?php
/*********************************************************************************
 * Autogenerated script
 * EasyDev 1.x copyright Patrick Mingard 2007-2010
 * Any modification of this code may alter the behaviour of EasyDev 2.x console
 ********************************************************************************/

require_once('../includes.php'); // includes of the generated script
require_once('object_<% echo $this->name;%>.class.php'); // include the class needed for the script
<%
foreach($this->fieldlist as $field){
  if($field->type == 'relation1N'){%>
require_once 'object_<% echo $field->label; %>.class.php';<%
  }
}%>
 
// first set a variable to indicate to which "mainmenu" this script belongs to in the administration console.
$adminMainMenu = <% echo $mainmenuid; %>;
 
// verify that the logged user has right to see this page
if(! $session_permissions[$adminMainMenu]){ // the user should not see this page because he do not has rights
  header('Location: '.CONSOLE_PATH.'index.php');
  exit;
}

if($_SERVER['REQUEST_METHOD'] == 'POST'){// if server method request == POST
  // delete all the ids the user checked in the object list
  foreach($_POST['deleteids'] as $deleteid){
    $object = <% echo $this->name; %>::findByPrimaryId($deleteid);
    if($object){
      $object->remove();

      $query = 'INSERT INTO '.LOGS.' (log) VALUES ("'.date('Y-m-d H:i').' : '.'Object \"<% echo $this->name;%>\" with id \"'.$deleteid.'\" deleted by '.$_SESSION[SESSION_NAME].'.")';
      mysql_query($query) or die('Error while inserting log.');
    }
  }
  
  // make a redirection on the same page
  header('Location: '.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU].'&action=confirmdelete');
  exit;
}
else{ // if the request_method == GET<%
foreach($this->fieldlist as $field){
  if($field->type == 'image'){%>
  if(isset($_GET['action']) && $_GET['action'] == 'view<% echo $this->name.$field->label;%>' && isset($_GET['id']) && ($objectToView = <% echo $this->name;%>::findByPrimaryId($_GET['id']))){
    echo '<html><head><link rel=stylesheet href="'.CONSOLE_PATH.'adminstyle.css" type="text/css"></head><body>'."\n".'<p class="center"><img src="'.$objectToView->getImage<% echo $field->label;%>Path().'" />'."\n".'<br /><a class="default" href="'.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU].'">'.Translator::translate('back_to_list_page').'</a></p>'."\n".'</body></html>';
    exit();
  }<%
  }
}%>

  // includes the header of the page
  include '../adminheader.php';
  
  echo '<script language="javascript">';
  echo 'function checkall(checked){';
  echo '  var checklist = document.getElementsByTagName("input");';
  echo '  for(i=0; i < checklist.length; i++){';
  echo '    if(checked){';
  echo '      checklist[i].checked = true;';
  echo '    }';
  echo '    else{';
  echo '      checklist[i].checked = false;';
  echo '    }';
  echo '  }';
  echo '}';
  echo '</script>';
  
  // if $_GET['action'] is set and is equal to "confirmdelete", print a message
  if(isset($_GET['action']) && $_GET['action'] == 'confirmDelete'){
    echo '<p><strong>'.htmlentities(Translator::translate('generator_confirm_delete'), ENT_COMPAT, 'UTF-8').'</strong></p>';
  }

  if(isset($_GET['action']) && $_GET['action'] == 'confirmmodify'){
    echo '<p><strong>'.Translator::translate('generator_confirm_modify').'</strong></p>';
  }

  // make some select lists to filter by relation1N target
  $objectsfilters = array();
<%
$needfilter = false;
foreach($this->fieldlist as $field){
  if($field->type == 'relation1N'){
    $needfilter = true;
  }
}
if($needfilter){%>
  echo '<p><strong>'.Translator::translate('generator_delete_page_filter_title').'</strong></p>'."\n";
  echo '<form class="easydevform marginleft" action="'.$_SERVER['REQUEST_URI'].'" method="get">'."\n";
  echo '<input type="hidden" name="'.CURRENTMENU.'" value="'.$_GET[CURRENTMENU].'" />'."\n";
  echo '<table>'."\n";<%
  foreach($this->fieldlist as $field){
    if($field->type == 'relation1N'){%>
  echo '  <tr>'."\n";
  echo '    <td><% echo $field->options['relationname']; %> : </td>'."\n";
  echo '    <td>';
  echo '      <select name="relation1N<% echo $field->options['relationname']; %>filter" onChange="this.form.submit();">'."\n";
  echo '      <option value=""></option>'."\n";
<%
$textfields = array();
$dbobject = null;
foreach($foreignobjectlist as $foreignobject){
	if($foreignobject->name == $field->label) $dbobject = $foreignobject;
}
foreach($dbobject->fieldlist as $f){
  switch($f->type){
  	case 'string':
  	case 'integer':
  	case 'double':
  	case 'date':
  	case 'datetime':
  		$textfields[] = $f->label;
  		break;
  }
}
	
      // now we have in $textfields all the fields that can be represented as text in a select list
%>
  // create the options of the select list
  $relatedobjectlist = <% echo $field->label; %>::find();
    
  foreach($relatedobjectlist as $object){
    echo '      <option value="'.$object->id.'"'.(isset($_GET['relation1N<% echo $field->options['relationname']; %>filter']) && $_GET['relation1N<% echo $field->options['relationname']; %>filter'] == $object->id ? ' selected="selected"' : '').'>';
<%
      $first = true;
      foreach($textfields as $textfield){
        if(!$first){%>
    echo ' - ';<%
        }
        $first = false;%>
    echo $object-><% echo $textfield; %>;<%
      }%>
    echo '</option>'."\n";
  }
  echo '      </select>'."\n";
  echo '    </td>'."\n";
  echo '  </tr>'."\n";<%
    }
  }%>
  echo '  <tr>'."\n";
  echo '    <td></td><td>'."\n";
  echo '<noscript><input type="submit" value="'.htmlentities(Translator::translate('filter'), ENT_COMPAT, 'UTF-8').'" /></noscript>'."\n";
  echo '    </td>'."\n";
  echo '  </tr>'."\n";
  echo '</table>'."\n";
  echo '</form>'."\n";

  // create the array for the filters<%
  foreach($this->fieldlist as $field){
    if($field->type == 'relation1N'){%>
  if(isset($_GET['relation1N<% echo $field->options['relationname']; %>filter']) && $_GET['relation1N<% echo $field->options['relationname']; %>filter'] != ''){
    $objectsfilters['<% echo $field->options['relationname']; %>'] = $_GET['relation1N<% echo $field->options['relationname']; %>filter'];
  }
<%
    }
  }
}
%>  
  echo '<p><strong>'.Translator::translate('generator_delete_page_title').'</strong></p>'."\n";
  // print all the objects that are in the database and print a checkbox to choose to delete it
?>
<form class="easydevform marginleft" action="<?php echo $_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.(isset($_GET[CURRENTMENU]) ? $_GET[CURRENTMENU] : ''); ?>" method="post">
<table class="deletescript">
  <tr valign="top">
    <td></td>
<?php
<%
foreach($this->fieldlist as $field){
  switch($field->type){
  case 'string':
  case 'integer':
  case 'double':
  case 'date':
  case 'image':
  case 'file':
  case 'datetime':%>
  echo '    <td><% echo $field->label; %></td>'."\n";<%
  }
}
%>
?>
  </tr>
<?php
  $objectlist = array();
  $objectnumber = 0;
  if(count($objectsfilters)){
    $objectlist = <% echo $this->name; %>::findByRelation1N($objectsfilters, (isset($_GET[NAVIGATION]) ? $_GET[NAVIGATION] : 0), 20);
    $objectnumber = <% echo $this->name; %>::countByRelation1N($objectsfilters);
  }
  else{
    $objectlist = <% echo $this->name; %>::find((isset($_GET[NAVIGATION]) ? $_GET[NAVIGATION] : 0), 20);
    $objectnumber = <% echo $this->name; %>::count();
  }
  
  foreach($objectlist as $object){
  echo '  <tr valign="top">'."\n";
  echo '    <td><input class="checkboxinput" type="checkbox" name="deleteids[]" value="'.$object->id.'" />'.$object->id.'</td>'."\n";
<%
$foundone = false;
$printedfieldcounter = 0;
foreach($this->fieldlist as $field){
  switch($field->type){
  case 'string':
  case 'integer':
  case 'date':
  case 'datetime':
  case 'double':%>
    echo '    <td>'.$object-><% echo $field->label; %>.'</td>';<%
    $printedfieldcounter++;
    break;
  case 'image':%>
    echo '    <td><a href="'.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.(isset($_GET[CURRENTMENU]) ? $_GET[CURRENTMENU] : '').'&amp;action=view<% echo $this->name.$field->label; %>&amp;id='.$object->id.'"><img src="'.$object->getImage<% echo $field->label;%>Path(50).'" /></a></td>';<%
    $printedfieldcounter++;
    break;
  case 'file':%>
    echo '    <td><a href="'.$object-><% echo $field->label; %>.'"><img src="'.CONSOLE_PATH.'file.jpg" alt="'.Translator::translate('download_file').'" /></a></td>';<%
    $printedfieldcounter++;
    break;
  }
}
%>

    echo '    <td><a class="default" href="objectadd_<% echo $this->name; %>.php?'.CURRENTMENU.'='.(isset($_GET[CURRENTMENU]) ? $_GET[CURRENTMENU] : '').'&objectid='.$object->id.(isset($_GET[NAVIGATION]) ? '&returnpage='.$_GET[NAVIGATION] : '').'">'.htmlentities(Translator::translate('modify'), ENT_COMPAT, 'UTF-8').'</a></td>'."\n";
    echo '  </tr>'."\n";
  }
  echo '  <tr>'."\n";
  echo '    <td><input type="checkbox" class="checkboxinput" onclick="checkall(this.checked)" />'.Translator::translate('all').'</td>'."\n";
  echo '    <td colspan="<% echo ($printedfieldcounter + 1);%>"><input class="bouton" type="submit" name="delete<% echo $this->name; %>submit" value="'.htmlentities(Translator::translate('delete'), ENT_COMPAT, 'UTF-8').'" /></td>'."\n";
  echo '    <td></td>'."\n";
  echo '  </tr>'."\n";
  echo '</table>'."\n";
  echo '</form>'."\n";

  // add "next" and "previous" buttons to navigate between the pages of the objects
  echo '<p>'.Translator::translate('pages').' : '.(isset($_GET[NAVIGATION]) && $_GET[NAVIGATION] > 0 ? '<a href="'.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU].'&amp;'.NAVIGATION.'='.(!isset($_GET[NAVIGATION]) || $_GET[NAVIGATION] - 20 <= 0 ? 0 : $_GET[NAVIGATION] - 20).<% foreach($this->fieldlist as $field){if($field->type == 'relation1N') echo '(isset($_GET[\'relation1N'.$field->options['relationname'].'filter\']) ? \'&relation1N'.$field->options['relationname'].'filter=\'.$_GET[\'relation1N'.$field->options['relationname'].'filter\'] : \'\').';}%>'"><img src="'.CONSOLE_PATH.'lfleche.jpg" alt="<" /></a> ' : '').((! isset($_GET[NAVIGATION]) && $objectnumber > 20) || isset($_GET[NAVIGATION]) && $_GET[NAVIGATION] + 20 < $objectnumber ? ' <a href="'.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU].'&amp;'.NAVIGATION.'='.((isset($_GET[NAVIGATION]) ? $_GET[NAVIGATION] : 0) + 20).<% foreach($this->fieldlist as $field){if($field->type == 'relation1N') echo '(isset($_GET[\'relation1N'.$field->options['relationname'].'filter\']) ? \'&relation1N'.$field->options['relationname'].'filter=\'.$_GET[\'relation1N'.$field->options['relationname'].'filter\'] : \'\').';}%>'"><img src="'.CONSOLE_PATH.'rfleche.jpg" alt=">" /></a>' : '').'</p>'."\n";

  // include the footer of the page
  include '../adminfooter.php';
}
?>

