<?php
<%


// ----- retrieve in $localtextfields and $remotetextfields the fields of $relationfield->label and $this->name that can be printed as text ------
$relationtextfields = array();
$localtextfields = array();

// find the labels that can be displayed as text from $this->fieldlist (local text fields)
foreach($this->fieldlist as $field){
  switch($field->type){
  case 'integer':
  case 'string':
  case 'double':
  case 'bool':
    // if the type of the field is int, bool, double, text, it can be printed as text
    array_push($localtextfields, $field->label);
    break;
  default:
    break;
  }
}

// need to select all the objects from object_$relationfield->label (relation text fields)
// WARNING : as we are in object $this->name, we do not know the fields of object $relationfield->label.
//           for this reason, need to analyze the table to select only text-printable fields

// find the labels which can be displayed as text from the table object_$relationfield->label
$query = 'DESCRIBE object_'.$relationfield->label;
$result = mysql_query($query) or die('Error while getting table description.<br />'.$query);

// this list will be used later to print a select list, so ids and other relations should not be taken into account.
while($line = mysql_fetch_array($result)){
  $triplet = substr($line['Type'], 0, 3);
  switch($triplet){
  case 'int':
  case 'tin':
  case 'tex':
  case 'dou':
    // if the type of the field is int, tinyint, text or double, it can be printed as text
    if($line['Field'] != 'id' && substr($line['Field'], 0, 6) != '1n_rel'){// remove the primary key and relations
      array_push($relationtextfields, $line['Field']);
    }
    break;
  default:
    break;
  }
} %>

/*********************************************************************************
 * Autogenerated script
 * EasyDev v.0.x copyright Patrick Mingard 2007
 * Any modification of this code can alter the behaviour of EasyDev v.0.x console
 ********************************************************************************/

require_once('includes.php');

// first set a variable to indicate to which "mainmenu" this script belongs to in the administration console.
$adminMainMenu = <% echo $mainmenuid; %>;

// verify that the logged user has right to see this page
if(! $session_permissions[$adminMainMenu]){ // the user should not see this page because he do not has rights
  header('Location: main.php');
  exit;
}

// if server method request == POST
if($_SERVER[REQUEST_METHOD] == 'POST'){
  // first remove all relations to insert new ones
  $query = 'DELETE FROM object_<% echo $relationfield->label; %>_<% echo $this->name; %>_<% echo $relationfield->options['relationname']; %>_nmrelation WHERE <%

if($foreign){
  %>id_<% echo $relationfield->label; %>="'.$_POST['selected'].'"';<%
}
else{
  %>id_<% echo $this->name; %>="'.$_POST['selected'].'"';<%
}
%>
  mysql_query($query) or die('Error while deleting relations.<br />'.$query);

  // insert all the relations
  foreach($_POST['relationids'] as $newrelation){
    $query = 'INSERT INTO object_<% echo $relationfield->label; %>_<% echo $this->name; %>_<% echo $relationfield->options['relationname']; %>_nmrelation (id_<% echo $relationfield->label; %>, id_<% echo $this->name; %>) '
<%
if($foreign){
  %>.'VALUES ("'.$_POST['selected'].'", "'.$newrelation.'")';
<%
}
else{
  %>.'VALUES ("'.$newrelation.'", "'.$_POST['selected'].'")';
<%
}
%>
    mysql_query($query) or die('Error while inserting new relations.<br />'.$query);
  }

  // make a redirection on the same page
  header('Location: '.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU]);
  exit;
}
else if(isset($_GET['action']) && $_GET['action'] == 'displayRelationObjects'){ // if $_GET['action'] == displayRelationObjects
  // verify that $_GET['selected'] is set (verification that the user chose an object for a relation
  if(isset($_GET['selected'])){
    // verify that the object exist
    $query = 'SELECT id FROM object_<% echo ($foreign ? $relationfield->label : $this->name); %> WHERE id="'.$_GET['selected'].'"';
    $result = mysql_query($query) or die('Error while selecting objects list.<br />'.$query);
    if(mysql_num_rows($result) > 0){ // there is at least one object with this id in database (in fact there cannot be more than one)
      // display all the objects that can be related to the one chosen.
      $query = 'SELECT id<%
// First find all the text-printable fields
$textfields = array();
if($foreign){
  // need to select all the objects from object_$this->name (local)
  $textfields = $localtextfields;
}
else{
  // need to select all the objects from object_$relationfield->label (remote)
  $textfields = $relationtextfields;
}

foreach($textfields as $t){
echo ', '.$t;
}
echo ' FROM object_';
if($foreign)
  echo $this->name;
else
  echo $relationfield->label;
%> ORDER BY id ASC';

      $resultObjects = mysql_query($query) or die('Error while selecting objects list.<br />'.$query);

      // now select all the ones that are already checked from relation
      $query = 'SELECT id_<% echo $relationfield->label; %>, id_<% echo $this->name; %> FROM object_<% echo $relationfield->label; %>_<% echo $this->name; %>_<% echo $relationfield->options['relationname']; %>_nmrelation '
<%
if($foreign){
  %>.' WHERE id_<% echo $relationfield->label; %>="'.$_GET['selected'].'"';
<%
}
else{
  %>.' WHERE id_<% echo $this->name; %>="'.$_GET['selected'].'"';
<%
}
%>
      $resultCheckedObjects = mysql_query($query) or die('Error while selecting objects list.<br />'.$query);

      // generate an array with all checked items
      $checkedItems = array();
      while($row = mysql_fetch_array($resultCheckedObjects)){
<%
if($foreign){
%>      array_push($checkedItems, $row['id_<% echo $this->name; %>']);<%
}
else{
%>      array_push($checkedItems, $row['id_<% echo $relationfield->label; %>']);
<%
}
%>
      }

      // generate the table with checkboxes for selecting the objects to relate
      include 'adminheader.php';

	
      echo '<form action="'.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU].'" method="post">'."\n";
      echo '<table class="form">'."\n";
      while($line = mysql_fetch_array($resultObjects)){
	  ?>
  <tr>
    <td><input type="checkbox" class="inputcheckbox" name="relationids[]" value="<?php echo $line['id']; ?>" <?php echo (in_array($line['id'], $checkedItems) ? ' checked="checked"' : ''); ?> /></td>
    <td><?php echo $line['id']; ?><%
foreach($textfields as $t){
%> - <?php echo $line['<% echo $t; %>']; ?><%
}
%></td>
  </tr>
      <?php
      } // end of while
      ?>
  <tr>
    <td><input type="hidden" name="selected" value="<?php echo $_GET['selected']; ?>" /></td>
    <td><input class="bouton" type="submit" name="validateRelations" value="<?php echo htmlentities($translator->translate('create_relations')); ?>" /></td>
  </tr>
</table>
</form>
      <?php
      include 'adminfooter.php';
    } // end of if(mysql_num_rows() > 0)
    else{
      // there is no object with this id, redirect on the default page
      header('Location: '.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU]);
      exit;
    }
  }// end of if(isset($_GET[selected]))
  else{
    // the selected item is not set, redirect on the default page
    header('Location: '.$_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU]);
    exit;
  }
} 
else{ // default case, print all the objects
  include 'adminheader.php';
<%
// depending on $foreign, need to select the local objects or foreign ones
$textfields = array(); // the fields of the database which can be diplayed as text. 
if($foreign){
  // need to select all the objects from the relation
  $textfields = $relationtextfields;
}
else{
  // need to select all the objects from object_$this->name
  $textfields = $localtextfields;
}
%>

  $query = 'SELECT id<%
foreach($textfields as $t){
%>, <% echo $t;
}
%> FROM object_<%
if($foreign)
  echo $relationfield->label;
else
  echo $this->name;
%> ORDER BY id ASC';
  $result = mysql_query($query) or die('Error while selecting objects list.<br />'.$query);
  //generate the select list with all objects selected
  echo '<table class="form">'."\n";
  while($line = mysql_fetch_array($result)){
    ?>
  <tr>
    <td><?php echo $line['id']; ?><%
foreach($textfields as $t){
  %> - <?php echo $line['<% echo $t; %>']; ?><%
}
%></td>
    <td><a class="default" href="<?php echo $_SERVER['PHP_SELF'].'?'.CURRENTMENU.'='.$_GET[CURRENTMENU]; ?>&action=displayRelationObjects&selected=<?php echo $line['id']; ?>"><?php echo $translator->translate('select'); ?></a></td>
  </tr><?php
  }
  echo '</table>'."\n";

  // include the footer of the page
  include 'adminfooter.php';
}
?>
